# Generated by Django 4.2.27 on 2025-12-04 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.PositiveIntegerField(default=1)),
                ('disponibilidade', models.CharField(blank=True, max_length=50)),
                ('modalidade', models.CharField(blank=True, max_length=50)),
                ('cr', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('creditos_cursados', models.PositiveIntegerField(default=0)),
                ('creditos_totais', models.PositiveIntegerField(default=180)),
                ('ac_cumpridas', models.PositiveIntegerField(default=0)),
                ('ac_total', models.PositiveIntegerField(default=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
