# Generated by Django 5.2.7 on 2025-12-05 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('EQUIPE', 'Equipe de competição'), ('ESTAGIO', 'Programa de estágio / inovação'), ('DIRETORIO', 'Diretório / Centro Acadêmico'), ('ENTIDADE', 'Entidade estudantil'), ('INICIACAO', 'Iniciação científica / pesquisa')], max_length=20)),
                ('nome', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('imagem', models.ImageField(blank=True, help_text='Imagem principal (ex: rio.jpg)', null=True, upload_to='oportunidades/')),
                ('imagem_mini', models.ImageField(blank=True, help_text='Miniatura (ex: riobotz-mini.png)', null=True, upload_to='oportunidades/minis/')),
                ('descricao', models.TextField()),
                ('texto_lateral', models.TextField(blank=True, help_text='Texto opcional exibido ao lado da imagem no detalhe (substitui o Lorem Ipsum).')),
                ('tipo', models.CharField(blank=True, help_text='Opcional: usado para Diretório, Entidade, etc.', max_length=100)),
                ('topicos_lista', models.TextField(blank=True, help_text='HTML opcional com lista de tópicos (ul/li) para estágios, iniciação, etc.')),
                ('destaque_home', models.BooleanField(default=False, help_text='Marque para aparecer na seção de destaques da home.')),
                ('resumo', models.CharField(blank=True, help_text='Texto curto para aparecer na lista geral (opcional).', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icone', models.CharField(help_text="Nome do ícone (ex: 'alternate_email', 'mail', 'person').", max_length=50)),
                ('texto', models.CharField(help_text='Texto de contato (ex: @riorobotz, email, nome da pessoa).', max_length=150)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='core.oportunidade')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cor', models.CharField(help_text="Classe de cor (ex: 'orange', 'blue', 'green').", max_length=30)),
                ('oportunidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.oportunidade')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
    ]
