# Generated by Django 5.2.7 on 2025-12-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='oportunidade',
            name='imagem_mini',
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='img',
            field=models.CharField(blank=True, help_text='Nome do arquivo da imagem principal (ex: rio.jpg).', max_length=200),
        ),
        migrations.AddField(
            model_name='oportunidade',
            name='img2',
            field=models.CharField(blank=True, help_text='Nome do arquivo da imagem secundária (ex: riobotz-mini.png).', max_length=200),
        ),
        migrations.AlterField(
            model_name='contato',
            name='icone',
            field=models.CharField(blank=True, help_text='Nome do ícone (ex: alternate_email, mail, person).', max_length=50),
        ),
        migrations.AlterField(
            model_name='contato',
            name='texto',
            field=models.CharField(help_text='Texto de contato (ex: @riobotz, email, nome da pessoa).', max_length=150),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='resumo',
            field=models.CharField(blank=True, help_text='Texto curto para listas.', max_length=255),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='texto_lateral',
            field=models.TextField(blank=True, help_text='Texto exibido ao lado da imagem principal no detalhe.'),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='tipo',
            field=models.CharField(blank=True, help_text='Opcional: tipo da oportunidade (Diretório, Empresa Júnior, etc.).', max_length=100),
        ),
        migrations.AlterField(
            model_name='oportunidade',
            name='topicos_lista',
            field=models.TextField(blank=True, help_text='HTML com lista de tópicos (ul/li) para estagios, iniciacao, etc.'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='cor',
            field=models.CharField(help_text='Classe de cor (ex: orange, blue, green).', max_length=30),
        ),
    ]
